Add feature_label_creation method
Also displays the following error that needs to be resolved:
ValueError: columns overlap but no suffix specified: Index(['shot - 0', 'shot - 1', 'shot - 2', 'shot - 3', 'shot - 4', 'shot - 5'], dtype='object')